const assert = require('node:assert/strict');

module.exports = async function ({openPage,base,passed}) {
  const client=await openPage(base+'/moov.html?lang=ko');
  const screenshot=async(name)=>{await new Promise(resolve=>setTimeout(resolve,350));await client.screenshot(name,false);};
  await client.send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:false});
  await client.wait(`document.querySelector('#app.screen-active') && window.MoovThemeSettings`,'app and preview module');
  await client.evaluate(`setTab('outing');openCourseDetail({id:'location-test-palace',name:'경복궁 투어',desc:'장소 이름으로 지도 조회',stops:['경복궁','경회루','광화문'],time:'3곳',author:'MOOV'})`);
  await client.wait(`document.querySelector('#course-detail-naver-map')?.dataset.mapState==='ready'`,'palace locations resolved',45000);
  assert.equal(await client.evaluate(`document.querySelectorAll('#course-detail-naver-map .naver-course-marker').length`),3);
  assert.match(await client.evaluate(`document.querySelector('[data-course-location-count]').textContent`),/3\/3/);
  const stops=await client.evaluate(`state.activeDetailCourse.stopDetails.map(p=>({name:p.name,lat:p.lat,lng:p.lng}))`);
  assert.ok(stops.every(p=>p.lat>37.57&&p.lat<37.59&&p.lng>126.97&&p.lng<126.99),'All palace stops belong near the palace, not a same-name restaurant');
  await screenshot('palace-detail-markers',false);
  passed('Name-only palace tour resolves three real NAVER places in order and displays their markers');
  await client.evaluate(`closeModal();setTab('profile');window.__originalTheme=state.theme;window.__originalConfig=JSON.stringify(state.themeConfig);openThemeSettings()`);
  const mode=name=>`#theme-settings [data-preview-choice="${name}"]`;
  assert.deepEqual(await client.evaluate(`Array.from(document.querySelectorAll('[data-preview-choice]'),b=>b.dataset.previewChoice)`),['윈도우','OTT','웰니스','테마','프라이빗']);
  await client.click(mode('OTT'));
  assert.equal(await client.evaluate(`document.querySelectorAll('#theme-scene .settings-ott-logos b').length`),4);
  assert.equal(await client.evaluate(`getComputedStyle(document.querySelector('#theme-scene .is-left')).backgroundColor`),'rgb(2, 2, 4)');
  await screenshot('settings-ott',false);
  await client.click(mode('웰니스'));
  await client.wait(`document.querySelector('#theme-scene .settings-yoga')?.naturalWidth>0`,'existing yoga image');
  assert.equal(await client.evaluate(`document.querySelector('#theme-scene .settings-yoga').parentElement.classList.contains('is-front')`),true,'Yoga belongs inside the front display');
  await screenshot('settings-wellness',false);
  await client.evaluate(`localStorage.setItem('moov-active-theme','forest')`);
  await client.click(mode('테마'));
  assert.equal(await client.evaluate(`document.querySelector('#theme-scene .settings-cabin').dataset.themeId`),'forest');
  assert.match(await client.evaluate(`document.querySelector('#theme-scene .is-front img').src`),/forest_1_front/);
  await screenshot('settings-current-theme',false);
  const brightness=[];
  for(const light of ['민트 앰비언트','따뜻한 독서등','콘텐츠 몰입등','수면 저조도']){
    await client.evaluate(`(()=>{const el=document.querySelector('#theme-light');el.value=${JSON.stringify(light)};el.dispatchEvent(new Event('change',{bubbles:true}));})()`);
    brightness.push(await client.evaluate(`getComputedStyle(document.querySelector('#theme-scene .settings-cabin')).filter`));
  }
  assert.equal(new Set(brightness).size,4);
  assert.equal(await client.evaluate(`getComputedStyle(document.querySelector('#theme-scene .settings-ambient-lines')).display`),'none');
  await client.evaluate(`(()=>{const el=document.querySelector('#theme-light');el.value='조명 끄기';el.dispatchEvent(new Event('change',{bubbles:true}));})()`);
  assert.equal(await client.evaluate(`getComputedStyle(document.querySelector('#theme-scene .settings-ambient-lines')).display`),'none');
  await screenshot('settings-lights-off',false);
  await client.click(mode('프라이빗'));
  assert.equal(await client.evaluate(`document.querySelector('#theme-tint').value`),'0');
  assert.equal(await client.evaluate(`document.querySelector('#theme-privacy').checked`),true);
  await screenshot('settings-private-dim',false);
  await client.evaluate(`closeModal()`);
  assert.equal(await client.evaluate(`JSON.stringify(state.themeConfig)===window.__originalConfig`),true,'Closing cancels drafts');
  await client.evaluate(`openThemeSettings()`);
  await client.click(mode('프라이빗'));
  await client.evaluate(`(()=>{const el=document.querySelector('#theme-temp');el.value=24;el.dispatchEvent(new Event('input',{bubbles:true}));})()`);
  assert.equal(await client.evaluate(`document.querySelector('#modal-actions .primary-button').textContent`),'확인');
  await client.click('#modal-actions .primary-button');
  assert.equal(await client.evaluate(`state.themeConfig.tint`),0);
  assert.equal(await client.evaluate(`state.themeConfig.temperature`),24);
  assert.equal(await client.evaluate(`state.theme===window.__originalTheme`),true,'Preview choice must not change the space mode');
  assert.equal(await client.evaluate(`document.querySelector('.mode-hero-visual .settings-cabin').dataset.previewMode`),'프라이빗');
  assert.equal(await client.evaluate(`document.querySelector('.mode-hero-visual .settings-cabin').style.getPropertyValue('--glass-opacity')`),'1');
  await screenshot('profile-saved-private',false);
  await client.evaluate(`openThemeSettings()`);
  assert.equal(await client.evaluate(`document.querySelector('#theme-tint').value`),'0');
  await client.click('#theme-privacy');
  assert.ok(Number(await client.evaluate(`document.querySelector('#theme-tint').value`))>0);
  await client.click(mode('웰니스'));
  await client.evaluate(`(()=>{const el=document.querySelector('#theme-light');el.value='따뜻한 독서등';el.dispatchEvent(new Event('change',{bubbles:true}));})()`);
  await screenshot('settings-wellness-front',false);
  await client.click('#modal-actions .primary-button');
  assert.equal(await client.evaluate(`document.querySelector('.mode-hero-visual .settings-cabin').dataset.previewMode`),'웰니스');
  assert.equal(await client.evaluate(`getComputedStyle(document.querySelector('.mode-hero-visual .settings-ambient-lines')).display`),'none');
  await screenshot('profile-saved-wellness',false);
  await client.send('Page.reload');
  await client.wait(`document.querySelector('#app.screen-active')`,'restore after reload');
  await client.evaluate(`setTab('profile')`);
  assert.equal(await client.evaluate(`document.querySelector('.mode-hero-visual .settings-cabin').dataset.previewMode`),'웰니스');
  assert.equal(await client.evaluate(`document.querySelector('.mode-hero-visual .settings-cabin').dataset.light`),'따뜻한 독서등');
  passed('Yoga stays in the front display; mint lines switch off; saved profile previews persist across reload');
  await client.evaluate(`loadCoursesFromDB()`);
  await client.evaluate(`state.outingSub='community';state.outingSort='latest';state.outingMapOpen=false;state.communityRecommendationOpen=false;setTab('outing');document.querySelectorAll('img[data-course-photos]').forEach(img=>img.loading='eager')`);
  await client.wait(`document.querySelectorAll('.course-visual img').length>0 && [...document.querySelectorAll('.course-visual img')].every(img=>{img.loading='eager';return img.complete&&img.naturalWidth>0})`,'community photos load including null-photo courses',45000);
  const photos=await client.evaluate(`({cards:document.querySelectorAll('.course-visual').length,images:document.querySelectorAll('.course-visual img').length,srcs:[...document.querySelectorAll('.course-visual img')].map(img=>img.getAttribute('src'))})`);
  assert.equal(photos.cards,photos.images,'Every community course has a cover');
  assert.ok(new Set(photos.srcs).size>1,'Available related covers provide variety');
  await screenshot('community-restored-photos',false);
  await client.evaluate(`document.querySelector('.course-visual img[data-representative="true"]')?.scrollIntoView({block:'center'})`);
  await screenshot('community-theme-photos',false);
  passed('Community covers load for every displayed course, with theme photos for missing originals');
};
