/* Invoked with: node tools/check_naver_maps.cjs http://localhost:3000 --login-survey */
const assert = require('node:assert/strict');

module.exports = async function({openPage,base,passed}) {
  const client=await openPage(base+'/moov.html?lang=ko',{survey:null,consent:null});
  await client.send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:false});
  await client.wait("!!document.querySelector('#location-consent-check')",'first login location consent');
  assert.equal(await client.evaluate("document.querySelector('[data-survey-action=consent]').disabled"),true);
  assert.equal(await client.evaluate("!!document.querySelector('#app.screen-active')"),false);
  assert.match(await client.evaluate("document.querySelector('#survey').textContent"),/성수역 테스트/);
  await client.screenshot('first-login-location-consent',false);
  await client.click('#location-consent-check');
  client.authFixture.failSave=true;
  await client.click('[data-survey-action=consent]');
  await client.wait("document.querySelector('#survey .survey-feedback')?.textContent.includes('저장하지 못')",'consent save failure');
  assert.equal(client.authFixture.locationConsent,null);
  client.authFixture.failSave=false;
  await client.click('[data-survey-action=consent]');
  await client.wait("!document.querySelector('#location-consent-check')",'consent saved before survey');
  assert.ok(client.authFixture.locationConsent);
  passed('First-login location agreement gates entry, clearly labels demo mode and retries failed persistence');
  await client.wait(`document.querySelector('#survey.screen-active [data-survey-option]')`,'first login survey');
  const option=(path,value)=>`#survey [data-survey-option="${path}"][data-value="${value}"]`;
  const action=name=>`#survey [data-survey-action="${name}"]`;
  await client.screenshot('survey-first-login', false);
  await client.click(option('categories','카페'));
  await client.click(option('categories','쇼핑'));
  await client.click(action('next'));
  assert.equal(await client.evaluate(`document.querySelectorAll('#survey fieldset').length`),2);
  await client.click(option('subcategories.카페','커피'));
  await client.click(action('back'));
  await client.click(option('categories','카페'));
  await client.click(action('next'));
  assert.equal(await client.evaluate(`document.querySelectorAll('#survey fieldset').length`),1);
  await client.click(option('subcategories.쇼핑','패션'));
  await client.click(action('next'));
  await client.click(option('preferredRegions','성수'));
  await client.click(action('next'));
  assert.equal(await client.evaluate(`!!document.querySelector(${JSON.stringify(option('avoidedRegions','성수'))})`),false);
  await client.click(action('back'));
  assert.equal(await client.evaluate(`document.querySelector(${JSON.stringify(option('preferredRegions','성수'))}).getAttribute('aria-pressed')`),'true');
  await client.click(option('preferredRegions','성수'));
  await client.click(option('preferredRegions','종로'));
  await client.click(action('next'));
  await client.click(option('avoidedRegions','성수'));
  await client.click(action('next'));
  await client.click(option('avoidances.foodRestrictions','견과류'));
  await client.evaluate(`(()=>{const input=document.querySelector('#survey-foods');input.value='고수, 매운 음식';input.dispatchEvent(new Event('input',{bubbles:true}));})()`);
  await client.click('#survey [data-language="en"]');
  assert.match(await client.evaluate(`document.querySelector('#survey h1').textContent`),/avoid/);
  assert.equal(await client.evaluate(`document.querySelector('#survey-foods').value`),'고수, 매운 음식');
  await client.screenshot('survey-exclusions-english', false);
  const fits=await client.evaluate(`(()=>{const host=document.querySelector('#survey'),button=host.querySelector('[data-survey-action="next"]'),r=button.getBoundingClientRect();return host.scrollWidth<=host.clientWidth && r.bottom<=innerHeight && r.top>0;})()`);
  assert.equal(fits,true,'Save action visible at mobile width without horizontal overflow');
  const footer=await client.evaluate(`(()=>{const skip=document.querySelector('#survey .survey-skip'),screen=document.querySelector('#survey');return {bottom:skip.getBoundingClientRect().bottom,height:innerHeight,screenBottom:screen.getBoundingClientRect().bottom};})()`);
  assert.ok(footer.bottom<=footer.height, 'Skip action visible: '+JSON.stringify(footer));
  client.authFixture.failSave=true;
  await client.click(action('next'));
  await client.wait(`document.querySelector('#survey .survey-feedback')?.textContent.includes('Could not save')`,'save failure preserves choices');
  assert.equal(client.authFixture.survey,null);
  assert.equal(await client.evaluate(`document.querySelector('#survey-foods').value`),'고수, 매운 음식');
  client.authFixture.failSave=false;
  await client.click(action('next'));
  await client.wait(`document.querySelector('#app.screen-active')`,'saved survey enters app');
  const saved=client.authFixture.survey;
  assert.deepEqual(saved.answers.categories,['쇼핑']);
  assert.deepEqual(saved.answers.subcategories,{'쇼핑':['패션']});
  assert.deepEqual(saved.answers.preferredRegions,['종로']);
  assert.deepEqual(saved.answers.avoidedRegions,['성수']);
  assert.deepEqual(saved.profile.excludedTags,['견과류','고수','매운 음식']);
  passed('First-login Q1–Q5: conditional details, mutually exclusive areas, bilingual choices and retry after failed save');
  await client.send('Page.reload');
  await client.wait(`typeof state==='object'&&state.isAuthenticated&&document.querySelector('#app.screen-active')&&state.surveyRecord?.status==='completed'`,'saved survey skipped on reload');
  await client.evaluate(`setTab('profile')`);
  await client.click('[data-action="edit-taste-survey"]');
  await client.wait(`document.querySelector('#survey.screen-active [data-survey-option]')`,'edit in profile');
  assert.equal(await client.evaluate(`document.querySelector(${JSON.stringify(option('categories','쇼핑'))}).getAttribute('aria-pressed')`),'true');
  await client.click(option('categories','카페'));
  await client.click(action('cancel'));
  assert.deepEqual(client.authFixture.survey.answers.categories,['쇼핑']);
  await client.click('[data-action="edit-taste-survey"]');
  await client.click(option('categories','관광'));
  for(let i=0;i<4;i++)await client.click(action('next'));
  await client.click(action('next'));
  await client.wait(`document.querySelector('#app.screen-active')&&state.surveyRecord?.profile.categories['관광']===1`,'edit saved');
  assert.equal(await client.evaluate('state.activeTab'),'profile');
  passed('Survey stays completed across reload; profile editing saves or cancels and returns to profile');
  await client.evaluate(`setTab('outing');state.recommendationPrefs={...defaultRecommendationPrefs(),budget:300000};runOutingRecommendation()`);
  const rec=await client.evaluate(`({ids:state.recommendationResultIds,allowed:state.recommendationResultIds.every(id=>MoovSurveyProfile.allowed(getCourse(id),state.surveyRecord.profile,getCourseTags(getCourse(id)))),containsExcluded:state.recommendationResultIds.includes('seongsu')})`);
  assert.ok(rec.ids.length>0);assert.equal(rec.allowed,true);assert.equal(rec.containsExcluded,false);
  await client.evaluate(`state.outingSort='preference';render()`);
  assert.equal(await client.evaluate(`getVisibleOutingCourses().some(c=>c.id==='seongsu')`),false);
  passed('Recommendation and taste ordering use saved preferences and exclude avoided areas');
  // A second isolated page exercises optional skipping and the load-error recovery path.
  const skipped=await openPage(base+'/moov.html?lang=ko',{survey:null});
  await skipped.wait(`document.querySelector('#survey.screen-active [data-survey-action="skip"]')`,'empty first login');
  await skipped.click(action('skip'));
  await skipped.wait(`document.querySelector('#app.screen-active')`,'skipped survey enters app');
  assert.equal(skipped.authFixture.survey.status,'skipped');
  assert.deepEqual(skipped.authFixture.survey.profile.categories,{});
  skipped.authFixture.failLoad=true;
  await skipped.send('Page.reload');
  await skipped.wait(`document.querySelector('#survey.screen-active [data-survey-action="retry"]')`,'load error offers retry');
  skipped.authFixture.failLoad=false;
  await skipped.click(action('retry'));
  await skipped.wait(`document.querySelector('#survey.screen-active [data-survey-action="skip"]')`,'incomplete survey reopens on next login');
  await skipped.click(option('categories','관광'));
  await skipped.click(action('skip'));
  await skipped.wait(`document.querySelector('#app.screen-active')`,'partial choices saved');
  await skipped.evaluate(`setTab('outing')`);
  await skipped.wait(`document.querySelector('#survey.screen-active')`,'outing opens incomplete survey');
  assert.equal(await skipped.evaluate(`document.querySelector(${JSON.stringify(option('categories','관광'))}).getAttribute('aria-pressed')`),'true');
  await skipped.click(action('skip'));
  await skipped.wait(`document.querySelector('#app.screen-active') && state.activeTab==='outing'`,'returns to requested outing without loop');
  await skipped.evaluate(`state.homeStep='mode';setTab('home')`);
  await skipped.wait(`document.querySelector('.moov-home-frame')?.contentDocument?.querySelector('[data-action="select-home-mode"][data-value="rent"]')`,'rental entry');
  await skipped.evaluate(`document.querySelector('.moov-home-frame').contentDocument.querySelector('[data-action="select-home-mode"][data-value="rent"]').click()`);
  await skipped.wait(`document.querySelector('#survey.screen-active')`,'rental opens incomplete survey');
  for(let i=0;i<5;i++)await skipped.click(action('next'));
  await skipped.wait(`document.querySelector('#app.screen-active') && document.querySelector('.moov-home-frame')?.contentWindow?.MOOVHome?.getState().homeStep==='booking'`,'completed survey resumes rental');
  assert.equal(skipped.authFixture.survey.status,'completed');
  passed('Skipped survey returns next login, preserves drafts, and resumes outing and rental after completion');
};
